Language bangla #108
allegro/tradukisto pull request #110
Opened 2023-08-23 12:02 UTC by ronisarkarexe

The addition of the Bangla (Bengali) language has been completed.

New language added. reference [](https://github.com/allegro/tradukisto/issues/108)

2023-08-23 15:04 UTC, dorians commented
please update readme

2023-08-23 15:20 UTC, dorians requested changes
thank you for your contribution! 
I reviewed it and left few comments

2023-08-23 15:20 UTC, dorians commented on src/test/groovy/pl/allegro/finance/tradukisto/ValueConvertersTest.groovy
> +        "bd"         || BANGALI_INTEGER
you use `bangle`, `bangli`, `bengali` and `bengali`, please choose one and make it consistent

2023-08-23 15:20 UTC, dorians commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/bangle/BangleValuesTest.groovy
> +    def "should convert #value to '#words' in Croatian"() {
leftovers (`Croatian`)

2023-08-23 15:20 UTC, dorians commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/bangle/BangleValuesTest.groovy
> +    def "should convert long #value to '#words' in Croatian"() {
leftovers (`Croatian`)

2023-08-23 15:20 UTC, dorians commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/bangle/BangleValues.java
> +                .put(11, "এগারো ")
why spaces here?

2023-08-23 15:20 UTC, dorians commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/bangle/BangleValues.java
> +                new SlavicPluralForms("একশো"),
this is not slavic language, maybe we should create another one for this language or change the name?

2023-08-25 09:14 UTC, ronisarkarexe commented on src/test/groovy/pl/allegro/finance/tradukisto/ValueConvertersTest.groovy
> +        "bd"         || BANGALI_INTEGER
choose bangla

2023-08-25 09:15 UTC, ronisarkarexe commented
I have changed the code, please check it now.

2023-08-28 10:11 UTC, dorians submitted a review, later dismissed
LGTM
cc @jglaszka

2023-08-30 15:21 UTC, jglaszka reviewed
I have question about test cases (see my comment in BanglaValuesTest.groovy). Also, in Bangla numbers are also separated by two digits as in Hindi?

2023-08-30 15:21 UTC, jglaszka commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/bangla/BanglaValuesTest.groovy
> +        2_141_123_731     | "একুশ বিলিয়ন চার কোটি এগারো লাখ তেইশ হাজার সাত শো একত্রিশ"
please add also case for         `Integer.MAX_VALUE         |  "something"`

2023-08-30 15:21 UTC, jglaszka commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/bangla/BanglaValuesTest.groovy
> +        2_000_000_000_000_000_000 | "বিশ লক্ষের পঞ্চঘাত"
also here please add test case for "  Long.MAX_VALUE            | """

2023-08-30 15:21 UTC, jglaszka commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/bangla/BanglaValuesTest.groovy
> +        123_456_789       | "একশো বাইশ কোটি তিনচল্লিশ লাখ পঁচাত্তর হাজার নব্বই"
Are these test cases valid? 
As I used translator একশো বাইশ কোটি means **122(?) crore**, but as I understand, 12.34.56.789 is **12 crore**, 34 lakh, 56 thousands + 789 - ` বারো কোটি চৌত্রিশ লাখ ছাপ্পান্ন হাজার সাত শো ঊননব্বই `

2023-08-31 09:47 UTC, ronisarkarexe commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/bangla/BanglaValuesTest.groovy
> +        123_456_789       | "একশো বাইশ কোটি তিনচল্লিশ লাখ পঁচাত্তর হাজার নব্বই"
solved

2023-09-06 15:41 UTC, jglaszka commented
@ronisarkarexe Hi, can you fix git conflicts?

2023-09-06 15:42 UTC, jglaszka commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/bangla/BanglaValues.java
> +                .put(1, "শূন্য")
Shouldn't it be 0?

2023-09-06 15:57 UTC, jglaszka commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/bangla/BanglaPluralForms.java
> +        return GenderType.NON_APPLICABLE;
needs to be imported:
```
import pl.allegro.finance.tradukisto.internal.languages.GenderType;
```

2023-09-06 16:01 UTC, jglaszka commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/bangla/BanglaValues.java
> +    }
This class needs to have `twoDigitsNumberSeparator` method implemented

2023-09-06 16:05 UTC, jglaszka requested changes
I ran your tests, 64/100 does not passes :( If counting in hindi is similar to bangla, you can get inspired by PR: https://github.com/allegro/tradukisto/pull/112

2023-09-13 03:27 UTC, ronisarkarexe commented
> I ran your tests, 64/100 does not passes :( If counting in hindi is similar to bangla, you can get inspired by PR: #112

I will check, thank for mention

2023-10-14 10:49 UTC, jglaszka commented
I resolved conflicts in your PR

2023-10-14 10:51 UTC, jglaszka commented on src/main/java/pl/allegro/finance/tradukisto/internal/Container.java
> +        TurkishValues values = new BanglaValues();
you need to change `TurkishValues` to `BanglaValues` like `BanglaValues values = new BanglaValues();`

2025-01-03 17:58 UTC, closed without merging