Add spanish support
allegro/tradukisto pull request #111
Opened 2023-08-25 13:27 UTC by luismateoh

I implemented `Integer` converter for spanish.
Could you kindly take a look at this pull request? I'm available for discussions.

2023-08-30 15:25 UTC, jglaszka commented
Hi, tomorrow I will look at your PR :)

2023-09-06 10:18 UTC, jglaszka commented
Oh, sorry, I was busy and forgot to check your PR. @bartlomiejgraczyk will review your code.

2023-09-06 18:20 UTC, jglaszka reviewed
I checked test cases (they looks good) and added some comments, more detailed review in core logic will be done by Bartłomiej.

2023-09-06 18:20 UTC, jglaszka commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/spanish/SpanishValues.java
> +        return "$";
I think it should be €, as it is official currency for Spain

2023-09-06 18:20 UTC, jglaszka commented on src/main/java/pl/allegro/finance/tradukisto/internal/Container.java
> +    public static Container spanishContainer(String... currency) {
Wow, nice.  :) In my opinion you can just use String instead of varargs operator.

2023-09-08 19:20 UTC, bartlomiejgraczyk requested changes
Thank you for your contribution. I'm leaving some remarks. Try to simplify code a little bit, make it more readable. I'm looking forward to your response.

2023-09-08 19:20 UTC, bartlomiejgraczyk commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/spanish/SpanishIntegerToWordsConverter.java
> +        }
this can be simplified, do you agree?
https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2023-09-08 19:20 UTC, bartlomiejgraczyk commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/spanish/SpanishThousandToWordsConverter.java
> +        return asWords(value, false);
```suggestion
        return asWords(value, HAS_NOT_NEXT_VALUE);
```

2023-09-08 19:20 UTC, bartlomiejgraczyk commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/spanish/SpanishThousandToWordsConverter.java
> +        }
https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2023-09-08 19:20 UTC, bartlomiejgraczyk commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/spanish/SpanishThousandToWordsConverter.java
> +                return format("%siún mil", asWords(tens).substring(0, 5));
what do you think about extracting those templates (e.g. `"%siún mil"`) to constants to avoid such magic strings?

2023-09-08 19:20 UTC, bartlomiejgraczyk commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/spanish/SpanishThousandToWordsConverter.java
> +        return list.contains(number);
shorter
```suggestion
        return (Math.abs(number) % 10) == 1;
```

2023-10-01 20:04 UTC, jglaszka commented
Hi @luismateoh, we added some comments for you in review. Can you take a look?

2023-10-06 07:03 UTC, jglaszka commented on README.md
> +* 🇪🇸 Spanish
in many languages we support only long

2023-10-06 07:09 UTC, jglaszka commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/spanish/SpanishValues.java
> +                .put(200, genderForms("doscientos", "doscientas", "doscientos"))
it is exception i think

2023-10-06 07:10 UTC, jglaszka commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/spanish/SpanishValues.java
> +                .put(200, genderForms("doscientos", "doscientas", "doscientos"))
in `exceptions()`

2023-10-06 20:28 UTC, luismateoh commented on src/main/java/pl/allegro/finance/tradukisto/internal/Container.java
> +    public static Container spanishContainer(String... currency) {
Agree, I can think of a future implementation once the first base code be integrate

2023-10-06 20:31 UTC, luismateoh commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/spanish/SpanishValues.java
> +                .put(200, genderForms("doscientos", "doscientas", "doscientos"))
yeah, is because is multi form number

2023-10-06 20:34 UTC, luismateoh commented
I carry out most of the suggestions you made, I appreciate the comments you made and agree with them

2023-10-12 16:37 UTC, bartlomiejgraczyk approved these changes

2023-10-13 09:19 UTC, merged