Added Indian flag and Hindi in the supported list.
allegro/tradukisto pull request #113
Opened 2023-09-06 06:44 UTC by girdharsourabh

Add

2023-09-06 15:43 UTC, jglaszka commented on README.md
> +* ![image](https://github.com/girdharsourabh/tradukisto/assets/5089894/7351341f-1640-4e42-a1b4-5af993c60962) Hindi
Please replace it with emoji 🇮🇳 instead of image.

2023-09-06 15:44 UTC, jglaszka requested changes
As mentioned above

2023-09-06 19:39 UTC, girdharsourabh commented
Done

2023-09-07 11:42 UTC, jglaszka approved these changes

2023-09-07 11:43 UTC, merged