Add Slovene support 🇸🇮
allegro/tradukisto pull request #134
Opened 2023-09-21 12:12 UTC by jglaszka

2023-09-22 08:22 UTC, jglaszka commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/slovene/SloveneValuesTest.groovy
> +
1000 is just "tisoč" and 1.000.000 is  "en milijon"
[9:34](https://allegro.slack.com/archives/D05U5F2C2AU/p1695368043619289)
1_000_000_000_000         | "en bilijon"
[9:34](https://allegro.slack.com/archives/D05U5F2C2AU/p1695368055931439)
3_000_000_000_000         | "trije bilijoni"





[9:34](https://allegro.slack.com/archives/D05U5F2C2AU/p1695368072736679)
2_000_000_000_000_000     | "dve bilijardi"
[9:34](https://allegro.slack.com/archives/D05U5F2C2AU/p1695368088587789)
1_000_000_000_000_000_000 | "en trilijon"


klemen.dacar
  [9:55 AM](https://allegro.slack.com/archives/D05U5F2C2AU/p1695369340119269)
5_000_000_000_000_000     | "pet bilijard"
[9:55](https://allegro.slack.com/archives/D05U5F2C2AU/p1695369355537079)
5_000_000_000_000_000_000 | "pet trilijonov"
[9:56](https://allegro.slack.com/archives/D05U5F2C2AU/p1695369379911269)
2_000_000_000_000_000_000 | "dva trilijona"
[9:56](https://allegro.slack.com/archives/D05U5F2C2AU/p1695369405169309)
3_000_000_000_000_000_000 | "trije trilijoni"

2023-10-23 18:02 UTC, bartlomiejgraczyk requested changes

2023-10-23 18:02 UTC, bartlomiejgraczyk commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/SlovenePluralForms.java
> +    }
```suggestion
    private boolean shouldUseSingularForm(Integer value) {
        return value == 1 || value % 100 == 1;
    }

    private boolean shouldUseDualForm(Integer value) {
        return value == 2 || value % 100 == 2;
    }

    private boolean shouldUsePluralForm(Integer value) {
        return Range.closed(3, 4).contains(value % 100);
    }
```

2023-10-25 09:08 UTC, jglaszka commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/SlovenePluralForms.java
> +    }
done in https://github.com/allegro/tradukisto/pull/134/commits/6a73c11e51ab9e0822c78588f4abb2cc63984e59

2023-11-02 12:32 UTC, bartlomiejgraczyk approved these changes

2023-11-02 12:35 UTC, merged