Add Spanish Support
allegro/tradukisto pull request #20
Opened 2018-05-03 23:32 UTC by carlosthe19916

2019-02-22 13:41 UTC, wjur commented
Hi @carlosthe19916 and @costris95! I'm sorry for the huge delay. There is another PR (#16) with Spanish, but it is not finished, too. Is any of you still willing to contribute?

2020-05-14 14:48 UTC, israteneda commented
There is an update on this pull request. Is any change necessary?

2023-07-07 13:19 UTC, jglaszka commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/spanish/SpanishValuesTest.groovy
> +
Hi, can you add more test cases? You can get inspired by `BrazilianPortugueseValuesTest` and fill with spanish translations.

2023-07-07 13:20 UTC, jglaszka requested changes
I would like to see more unit tests.

2023-07-07 18:15 UTC, carlosthe19916 commented
Hey, this PR got lost from my radar the last 5 years. I'm no longer interested in continuing with this PR. I'm happy to close it without merging it.

2023-07-10 08:24 UTC, jglaszka commented
> Hey, this PR got lost from my radar the last 5 years. I'm no longer interested in continuing with this PR. I'm happy to close it without merging it.

Okay, I understand. Sorry for the delay. This project was neglected by the past owners, but currently I started to clean it up and take care of the project. 
If I will apply some changes, can I merge your code in future?

2023-07-10 08:41 UTC, carlosthe19916 commented
> > Hey, this PR got lost from my radar the last 5 years. I'm no longer interested in continuing with this PR. I'm happy to close it without merging it.
> 
> Okay, I understand. Sorry for the delay. This project was neglected by the past owners, but currently I started to clean it up and take care of the project. If I will apply some changes, can I merge your code in future?

Sure, you can use the code in this PR as you need.

2023-07-10 08:42 UTC, jglaszka commented
Thank you! 😊

2023-10-11 09:33 UTC, GHim9182 commented
Hi @jglaszka, I need the Spanish support for my company. After I implemented Italian and Dutch conversions I would love to help also in the Spanish one.
I see there are different PR, could you kindly update me on the status of the ES support and in case, which  branch I should use?

Thanks.

2023-10-11 09:36 UTC, GHim9182 commented
@jglaszka sorry, just noticed it's now under development and review in #111 . nvm

2023-10-13 09:26 UTC, closed without merging

2023-10-13 09:26 UTC, jglaszka commented
@GHim9182 Support for spanish was released in https://github.com/allegro/tradukisto/releases/tag/v2.6.0