Added Serbian Cyrillic support with additional bug fixes
allegro/tradukisto pull request #43
Opened 2021-09-30 14:52 UTC by aleksandarni

2021-09-30 18:56 UTC, MaciejLipinski requested changes
Thank you for your second contribution! There's a couple of things that need fixing, please see the comments

2021-09-30 18:56 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/MoneyConverters.java
> -    TURKISH_BANKING_MONEY_VALUE(turkishContainer().getBankingMoneyConverter()),
revert moving Turkish converter declaration; the order is a mess, but moving just one converter doesn't help

2021-09-30 18:56 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/ValueConverters.java
> +    FRENCH_INTEGER(frenchContainer().getNumbersConverter());
change `;` to `,`

2021-09-30 18:56 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/MoneyConverters.java
> +    SERBIAN_CYRILLIC_BANKING_MONEY_VALUE(serbianCyrillicContainer().getBankingMoneyConverter());
change `;` to `,`

2021-09-30 18:56 UTC, MaciejLipinski commented on src/test/groovy/pl/allegro/finance/tradukisto/MoneyConvertersTest.groovy
> +import static pl.allegro.finance.tradukisto.MoneyConverters.SERBIAN_CYRILLIC_BANKING_MONEY_VALUE
rearrange imports, now they're not ordered alphabetically and there's a duplicate `SERBIAN_BANKING_MONEY_VALUE` on line 17

2021-09-30 18:56 UTC, MaciejLipinski commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/RegularPluralFormsTest.groovy
> -import pl.allegro.finance.tradukisto.internal.languages.GenderType
nice find!

2021-10-01 14:25 UTC, aleksandarni commented
@MaciejLipinski Thank you for the suggestions. I believe I fixed/improved all of them.

2021-10-02 07:32 UTC, MaciejLipinski approved these changes

2021-10-02 08:35 UTC, merged