46 Added getValueConverters(Locale locale) and getByLanguageCode(String languageCode) methods
allegro/tradukisto pull request #47
Opened 2021-10-12 09:50 UTC by altro3

Fixed #46

2021-10-15 08:16 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/ValueConverters.java
> +            throw new IllegalArgumentException("Locale is null");
use `verifyNotNull(locale)`, see line 49

2021-10-15 08:20 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/ValueConverters.java
> +    public ValueConverters getByLocale(Locale locale) {
returning `ENGLISH_INTEGER` by default is implicit; it would be better to change this method to `getByLocaleOrDefault(Locale locale, ValueConverters defaultConverter)` and return the passed converter if nothing matches the passed locale

2021-10-15 08:22 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/ValueConverters.java
> +    public ValueConverters getByLanguageCode(String languageCode) {
change this method to `private`, this way there's only one entry to it and you can remove the null/empty check

2021-10-15 08:25 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/ValueConverters.java
> +        switch( languageCode.toLowerCase(Locale.ENGLISH) ){
This way it's very easy to forget about adding a new switch branch when adding a new language. It'd be better to add a new required field `String languageCode` to `ValueConverters` and then find the converter that has the matching language code.

2021-10-15 12:30 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/ValueConverters.java
> +        return BY_LANGUAGE_CODE.getOrDefault(languageCode, defaultConverters);
change to:
```
return Arrays.stream(values())
                .filter(it -> it.languageCodes.contains(languageCode))
                .findFirst()
                .orElse(defaultConverter);
```
this way `BY_LANGUAGE_CODE` can be removed, along with the `static` block

2021-10-15 12:31 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/ValueConverters.java
> +    public static ValueConverters getByLanguageCode(String languageCode, ValueConverters defaultConverters) {
rename to `getByLanguageCodeOrDefault`, also rename last arg to `defaultConverter` (singular)

2021-10-15 12:33 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/ValueConverters.java
> +        if (languageCode == null || languageCode.isEmpty()) {
change to:
```
verifyNotNull(languageCode);
verify(!languageCode.isEmpty());
```

2021-10-15 12:34 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/ValueConverters.java
> +
remove empty line

2021-10-15 12:37 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/ValueConverters.java
> +        if (Strings.isNullOrEmpty(locale.getScript())) {
extract method `boolean hasSpecifiedScript(Locale locale)`

2021-10-15 12:38 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/ValueConverters.java
> +            languageCode = new Locale.Builder().setLanguage(locale.getLanguage()).setScript(locale.getScript()).build().toString();
extract method `String getLanguageCodeFor(String language, String script)`

2021-10-15 12:40 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/ValueConverters.java
> +    SERBIAN_CYRILLIC_INTEGER(serbianCyrillicContainer().getNumbersConverter(), new Locale.Builder().setLanguage("sr").setScript("Cyrl").build().toString()),
thank you for the in-depth research on this!

2021-10-15 12:42 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/ValueConverters.java
> +    public ValueConverters getByLanguageCode(String languageCode) {
alright, I agree it might be useful too.

2021-10-15 12:44 UTC, MaciejLipinski commented on src/test/groovy/pl/allegro/finance/tradukisto/ValueConvertersTest.groovy
> +
Add test that shows `VerifyException` is thrown when `null` or `""` is supplied

2021-10-15 14:24 UTC, MaciejLipinski requested changes
almost there, one last thing I found

2021-10-15 14:24 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/ValueConverters.java
> +    private static boolean hasSpecifiedScript(Locale locale) {
the name suggests inverse behavior. Negate the expression and change order in the if/else, or rename this method to `doesNotHaveSpecifiedScript` (but I think negating and changing if will be nicer)

2021-10-15 15:13 UTC, altro3 commented on src/main/java/pl/allegro/finance/tradukisto/ValueConverters.java
> +    private static boolean hasSpecifiedScript(Locale locale) {
Fixed

2021-10-18 07:15 UTC, MaciejLipinski approved these changes

2021-10-18 07:30 UTC, merged