add long value converters
allegro/tradukisto pull request #48
Opened 2021-10-15 11:27 UTC by MaciejLipinski

Fixes https://github.com/allegro/tradukisto/issues/37 for English and Polish.
Added ignored stub tests for other languages – long support for those will have to be added separately.

2022-05-06 15:19 UTC, tokninski requested changes

2022-05-06 15:19 UTC, tokninski commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/czech/CzechNumberToWordsConverterTest.groovy
> +class CzechNumberToWordsConverterTest extends Specification {
Isn't it still `CzechIntegerToWordsConverter`?

2022-05-06 15:19 UTC, tokninski commented on src/main/java/pl/allegro/finance/tradukisto/internal/Container.java
> +                this.integerConverter,
`this.` is optional here

2022-05-20 16:06 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/LongValueConverters.java
> +public enum LongValueConverters {
As I can't change the existing API, `ValueConverters` is stuck with the `public String asWords(Integer value)` method. If I moved the long converters to `ValueConverters`, they would have it too (it could work, if a little silly). Worse, the existing integer converters would have to have the new `public String asWords(Long value)` method – that would make no sense. It would have to throw `UnsupportedOperationException`. The better solution here IMO is to separate integer from long converters and have separate contracts for them.

2022-05-20 16:07 UTC, MaciejLipinski commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/czech/CzechValuesTest.groovy
>      def "should convert #value to '#words' in Czech"() {
they do, the new ignored test is below. I added ignored tests for languages that don't (as of yet) have their long converters.

2022-05-20 16:09 UTC, MaciejLipinski commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/czech/CzechNumberToWordsConverterTest.groovy
> +class CzechNumberToWordsConverterTest extends Specification {
right, reverting rename

2022-05-20 16:09 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/internal/Container.java
> +                this.integerConverter,
removed

2022-07-22 10:40 UTC, tokninski approved these changes

2022-07-25 12:29 UTC, merged