bugfix/prevent base number remapping
allegro/tradukisto pull request #55
Opened 2022-01-26 17:12 UTC by MaciejLipinski

2022-01-26 17:24 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/portuguese/PortugueseThousandToWordsConverter.java
> +        return format("%s e %s", asWords(hundreds, true), asWords(tensWithUnits));
`hasNextNumber` was always `true`, since all full hundreds (100, 200, 300...) are base numbers or an exception (100 is an exception in Portuguese), so they are handled in line 36 and 41

2022-01-28 22:32 UTC, jglaszka commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/support/BaseNumbersBuilderTest.groovy
> +    }
You can also add test:
```   
   def 'i dont know which name is suitable for this test ;)' () {
        given:
        builder.put(1, new GenderForms("some form"))

        when:
        builder.put(1, "some other form")

        then:
        thrown(NumberAlreadyMappedException)
    }
  ```

2022-01-28 22:33 UTC, jglaszka commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/support/BaseNumbersBuilderTest.groovy
> +    def builder = baseNumbersBuilder()
I think it can be not good practice to use shared not-immutable object over multiple test cases.

2022-01-28 23:10 UTC, jglaszka commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/portuguese/PortugueseThousandToWordsConverter.java
> +        return format("%s e %s", asWords(hundreds, true), asWords(tensWithUnits));
hm, can we add a test for that one specific case?

2022-01-28 23:13 UTC, jglaszka requested changes
I think all changes are okay, but please fix the tests - if you think it is needed

2022-01-30 10:22 UTC, dorians approved these changes

2022-01-31 08:56 UTC, MaciejLipinski commented on src/main/java/pl/allegro/finance/tradukisto/internal/languages/portuguese/PortugueseThousandToWordsConverter.java
> +        return format("%s e %s", asWords(hundreds, true), asWords(tensWithUnits));
they are tested in `BrazilianPortugueseValuesTest.groovy:59-67` – test cases for full hundred numbers (100 to 900)

2022-01-31 08:58 UTC, MaciejLipinski commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/support/BaseNumbersBuilderTest.groovy
> +    }
good idea. Also added test for String -> GenderForm

2022-01-31 09:01 UTC, MaciejLipinski commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/support/BaseNumbersBuilderTest.groovy
> +    def builder = baseNumbersBuilder()
right. Moved initialization to `setup` method

2022-01-31 09:13 UTC, jglaszka approved these changes

2022-01-31 09:50 UTC, merged