Update UkrainianValues.java
allegro/tradukisto pull request #68
Opened 2023-05-02 12:05 UTC by rudinew

edited value "пятдесят" -> "п'ятдесят"

2023-07-03 15:48 UTC, bgalek approved these changes

2023-07-03 17:09 UTC, jglaszka commented
Hello @rudinew! Thanks for PR. 
I checked your fork, but some of the tests does not pass (it still requires пятдесят instead of п'ятдесят). Can you fix these tests cases to valid form and push?

2023-07-03 17:15 UTC, jglaszka requested changes
Hello @rudinew! Thanks for PR.
I checked your fork, but some of the tests does not pass (it still requires пятдесят instead of п'ятдесят). Can you update these tests cases to valid form and push?

2023-07-04 16:36 UTC, jglaszka approved these changes

2023-07-04 16:37 UTC, merged