Dutch language integration
allegro/tradukisto pull request #69
Opened 2023-05-31 14:40 UTC by GHim9182

2023-05-31 15:00 UTC, GHim9182 commented
Hi @MaciejLipinski, could you kindly take a look at this pull request? I'm available for discussions.

2023-06-29 12:19 UTC, jglaszka commented
Hi @GHim9182, sorry for no answer - temporarily there was no person taking care of this project. 
I will take a look at your code this week.

2023-07-02 09:02 UTC, jglaszka commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/dutch/DutchValuesTest.groovy
> +        24190      | "vierentwintigduizendhonderdnegentig"
Can you add test case also for 24191?

2023-07-02 09:22 UTC, jglaszka commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/dutch/DutchValuesTest.groovy
> +        69         | "negenenzestig"
Can you add test case also for 62?

2023-07-02 09:25 UTC, jglaszka commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/dutch/DutchValuesTest.groovy
> +        1000       | "duizend"
Please add test case also for 1001

2023-07-02 09:27 UTC, jglaszka requested changes
Before I will check whole code, we need to add more test cases in unit tests.

2023-07-06 08:27 UTC, GHim9182 commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/dutch/DutchValuesTest.groovy
> +        24190      | "vierentwintigduizendhonderdnegentig"
Done

2023-07-06 08:28 UTC, GHim9182 commented on src/test/groovy/pl/allegro/finance/tradukisto/internal/languages/dutch/DutchValuesTest.groovy
> +        1000       | "duizend"
Done

2023-07-06 09:10 UTC, jglaszka commented
I will take a look at this today.

2023-07-06 16:44 UTC, jglaszka approved these changes
Looks good to me. :) tommorow I will merge this

2023-07-07 13:13 UTC, merged